# scheme: https://raw.githubusercontent.com/prefix-dev/pixi/refs/heads/main/schema/schema.json
[project]
authors = ["JafarAbdi <jafar.uruc@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "plotjuggler-zenoh"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
configure-plotjuggler = "cmake -GNinja -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=.pixi/envs/default -S external/plotjuggler .build/plotjuggler"
build-plotjuggler = { cmd = "cmake --build .build/plotjuggler", depends_on = [
  "configure-plotjuggler",
] }
# Why --prefix .pixi/envs/default doesn't work?
install-plotjuggler = { cmd = "cmake --install .build/plotjuggler --prefix .pixi/envs/default", depends_on = [
  "build-plotjuggler",
] }

configure = "cmake -GNinja -DCMAKE_BUILD_TYPE=RelWithDebInfo -S . .build/plotjuggler-zenoh"
build = { cmd = "cmake --build .build/plotjuggler-zenoh", depends_on = ["configure"] }
install = { cmd = "cmake --install .build/plotjuggler-zenoh --prefix .pixi/envs/default", depends_on = ["build"] }

plotjuggler = "plotjuggler --nosplash"


[dependencies]
ninja = ">=1.12.1,<2"
cmake = ">=3.30.5,<4"
lld = ">=19.1.3,<20"
qt = ">=5.15.8,<6"

[activation]
env = { LD_LIBRARY_PATH = "$LD_LIBRARY_PATH:$PIXI_PROJECT_ROOT/.pixi/envs/default/lib" }
